/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlockTimeSchedulerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, folders) {
    super(app, inputEl);
    this.folders = folders;
  }
  getSuggestions(query) {
    const lowerCaseQuery = query.toLowerCase();
    return [...this.folders].filter(
      (folder) => folder.toLowerCase().includes(lowerCaseQuery)
    );
  }
  renderSuggestion(folder, el) {
    el.setText(folder);
  }
  selectSuggestion(folder, _evt) {
    this.setValue(folder);
    this.close();
  }
};
var DEFAULT_SETTINGS = {
  startHour: 6,
  endHour: 22,
  defaultView: "day",
  taskPattern: "- \\[.\\]",
  useObsidianTheme: true,
  enableNotifications: true,
  enableReminderBefore: true,
  reminderMinutesBefore: 15,
  enableDeadlineReminders: true,
  deadlineTags: "#prazo, #deadline",
  deadlineReminderDays: 3,
  deadlineReminderHour: 9,
  notifyTextEarlyTask: "\u23F0 Em {min} min: {task}",
  notifyTextOnTimeTask: "\u{1F4C5} Agora: {task}",
  notifyTextDeadlineEarly: "\u{1F6A8} Prazo em {min} min: {task}",
  notifyTextDeadlineNow: "\u{1F6A8} Prazo AGORA: {task}",
  notifyTextDeadlineToday: "\u{1F6A8} Prazo HOJE: {task}",
  notifyTextDeadlineDays: "\u26A0\uFE0F Prazo em {days} dia(s): {task}",
  scanFolders: "",
  taskCreationFolder: "Task"
};
var TRANSLATIONS = {
  "en": {
    "view-title": "Block Time Scheduler",
    "day-view": "Day View",
    "week-view": "Week View",
    "today": "Today",
    "unscheduled-tasks": "Unscheduled Tasks",
    "no-tasks": "No tasks scheduled",
    "create-task": "Create task",
    "hours": "Hours",
    "priority-high": "High",
    "priority-medium": "Medium",
    "priority-low": "Low",
    "task-completed": "Task completed",
    "task-uncompleted": "Task uncompleted",
    // Dias da semana
    "sunday": "Sun",
    "monday": "Mon",
    "tuesday": "Tue",
    "wednesday": "Wed",
    "thursday": "Thu",
    "friday": "Fri",
    "saturday": "Sat",
    // Configurações
    "settings-agenda": "Agenda",
    "settings-appearance": "Appearance",
    "settings-notifications": "Notifications",
    "settings-deadlines": "Deadlines",
    "settings-texts": "Texts",
    "start-hour": "Start hour",
    "start-hour-desc": "Hour when the agenda starts",
    "end-hour": "End hour",
    "end-hour-desc": "Hour when the agenda ends",
    "default-view": "Default view",
    "default-view-desc": "Default view when opening the agenda",
    "use-obsidian-theme": "Use Obsidian theme",
    "use-obsidian-theme-desc": "Use colors from your current Obsidian theme",
    "enable-notifications": "Enable notifications",
    "enable-notifications-desc": "Show desktop notifications for tasks",
    "notification-early": "Early reminder",
    "notification-early-desc": "X minutes before task",
    "notification-ontime": "On time",
    "notification-ontime-desc": "Exact moment of task",
    "notification-deadline-early": "Deadline \u2014 minutes before",
    "notification-deadline-early-desc": "X minutes before deadline",
    "notification-deadline-now": "Deadline \u2014 now",
    "notification-deadline-now-desc": "Exact deadline time",
    "notification-deadline-today": "Deadline \u2014 today",
    "notification-deadline-today-desc": "Deadline is today (no time)",
    "notification-deadline-days": "Deadline \u2014 days",
    "notification-deadline-days-desc": "X days until deadline",
    "scan-folders": "Scan folders",
    "scan-folders-desc": "Folders to scan for tasks (comma separated)",
    "no-folders-selected": "No folders selected (entire vault)",
    "placeholders": "Placeholders: {task} {min} {days} {time} {endTime} {file} {date}",
    "advanced-folder-mode": "Advanced folder selection mode",
    "advanced-folder-mode-desc": "Use advanced folder picker with tree view (disable for simple text mode)",
    "info-title": "How task creation and editing works:",
    "info-para1": "Click an empty slot in the hour grid \u2014 opens the Tasks plugin modal to create a new task. The task is saved automatically to the daily note for the selected day, using the folder and format configured in the Daily Notes plugin (Settings \u2192 Daily Notes).",
    "info-para2": "Double-click a task \u2014 opens the Tasks modal to edit the existing task (date, time, recurrence, etc.). Changes are saved directly to the original file.",
    "info-para3": "Checkbox \u2014 mark or unmark a task. If the Tasks plugin is installed, uses its logic (automatic recurrence, done date, etc.). Otherwise, uses the plugin's internal logic.",
    "info-footer": "Requires the Tasks plugin (obsidian-tasks-plugin) to create and edit tasks. Without it, only the checkbox toggle works."
  },
  "pt": {
    "view-title": "Agenda de Blocos de Tempo",
    "day-view": "Vis\xE3o Di\xE1ria",
    "week-view": "Vis\xE3o Semanal",
    "today": "Hoje",
    "unscheduled-tasks": "Tarefas sem hor\xE1rio definido",
    "no-tasks": "Nenhuma tarefa agendada",
    "create-task": "Criar tarefa",
    "hours": "Horas",
    "priority-high": "Alta",
    "priority-medium": "M\xE9dia",
    "priority-low": "Baixa",
    "task-completed": "Tarefa conclu\xEDda",
    "task-uncompleted": "Tarefa n\xE3o conclu\xEDda",
    // Dias da semana
    "sunday": "Dom",
    "monday": "Seg",
    "tuesday": "Ter",
    "wednesday": "Qua",
    "thursday": "Qui",
    "friday": "Sex",
    "saturday": "S\xE1b",
    // Configurações
    "settings-agenda": "Agenda",
    "settings-appearance": "Apar\xEAncia",
    "settings-notifications": "Notifica\xE7\xF5es",
    "settings-deadlines": "Prazos",
    "settings-texts": "Textos",
    "start-hour": "Hora inicial",
    "start-hour-desc": "Hora quando a agenda come\xE7a",
    "end-hour": "Hora final",
    "end-hour-desc": "Hora quando a agenda termina",
    "default-view": "Vis\xE3o padr\xE3o",
    "default-view-desc": "Vis\xE3o padr\xE3o ao abrir a agenda",
    "use-obsidian-theme": "Usar tema do Obsidian",
    "use-obsidian-theme-desc": "Usar cores do seu tema atual do Obsidian",
    "enable-notifications": "Ativar notifica\xE7\xF5es",
    "enable-notifications-desc": "Mostrar notifica\xE7\xF5es na \xE1rea de trabalho para tarefas",
    "notification-early": "Lembrete antecipado",
    "notification-early-desc": "X minutos antes da tarefa",
    "notification-ontime": "No hor\xE1rio",
    "notification-ontime-desc": "Momento exato da tarefa",
    "notification-deadline-early": "Prazo \u2014 minutos antes",
    "notification-deadline-early-desc": "X minutos antes do prazo",
    "notification-deadline-now": "Prazo \u2014 agora",
    "notification-deadline-now-desc": "Hor\xE1rio exato do prazo",
    "notification-deadline-today": "Prazo \u2014 hoje",
    "notification-deadline-today-desc": "Prazo \xE9 hoje (sem hor\xE1rio)",
    "notification-deadline-days": "Prazo \u2014 dias",
    "notification-deadline-days-desc": "Faltam X dias para o prazo",
    "scan-folders": "Pastas para escanear",
    "scan-folders-desc": "Pastas para procurar tarefas (separadas por v\xEDrgula)",
    "no-folders-selected": "Nenhuma pasta selecionada (vault inteiro)",
    "placeholders": "Placeholders: {task} {min} {days} {time} {endTime} {file} {date}",
    "advanced-folder-mode": "Modo avan\xE7ado de sele\xE7\xE3o de pastas",
    "advanced-folder-mode-desc": "Use o seletor avan\xE7ado com \xE1rvore de pastas (desative para modo simples com texto)",
    "info-title": "Como funciona a cria\xE7\xE3o e edi\xE7\xE3o de tasks:",
    "info-para1": "Clique em um slot vazio na grade de horas \u2014 abre o modal do plugin Tasks para criar uma nova task. A task \xE9 salva automaticamente no Daily Note do dia clicado, respeitando a pasta e formato configurados no plugin Daily Notes do Obsidian (Configura\xE7\xF5es \u2192 Daily Notes).",
    "info-para2": "Duplo-clique em uma task \u2014 abre o modal do Tasks para editar a task existente (data, hora, recorr\xEAncia, etc.). As altera\xE7\xF5es s\xE3o salvas diretamente no arquivo original.",
    "info-para3": "Checkbox \u2014 marca ou desmarca a task. Se o plugin Tasks estiver instalado, usa a l\xF3gica dele (recorr\xEAncia autom\xE1tica, done date, etc.). Caso contr\xE1rio, usa l\xF3gica manual interna.",
    "info-footer": "Requer o plugin Tasks (obsidian-tasks-plugin) para criar e editar. Sem ele, apenas o toggle por checkbox funciona."
  },
  "es": {
    "view-title": "Agenda de Bloques de Tiempo",
    "day-view": "Vista Diaria",
    "week-view": "Vista Semanal",
    "today": "Hoy",
    "unscheduled-tasks": "Tareas sin horario definido",
    "no-tasks": "No hay tareas programadas",
    "create-task": "Crear tarea",
    "hours": "Horas",
    "priority-high": "Alta",
    "priority-medium": "Media",
    "priority-low": "Baja",
    "task-completed": "Tarea completada",
    "task-uncompleted": "Tarea no completada",
    // Dias da semana
    "sunday": "Dom",
    "monday": "Lun",
    "tuesday": "Mar",
    "wednesday": "Mi\xE9",
    "thursday": "Jue",
    "friday": "Vie",
    "saturday": "S\xE1b",
    // Configurações
    "settings-agenda": "Agenda",
    "settings-appearance": "Apariencia",
    "settings-notifications": "Notificaciones",
    "settings-deadlines": "Plazos",
    "settings-texts": "Textos",
    "start-hour": "Hora de inicio",
    "start-hour-desc": "Hora cuando la agenda comienza",
    "end-hour": "Hora final",
    "end-hour-desc": "Hora cuando la agenda termina",
    "default-view": "Vista predeterminada",
    "default-view-desc": "Vista predeterminada al abrir la agenda",
    "use-obsidian-theme": "Usar tema de Obsidian",
    "use-obsidian-theme-desc": "Usar colores de tu tema actual de Obsidian",
    "enable-notifications": "Activar notificaciones",
    "enable-notifications-desc": "Mostrar notificaciones de escritorio para tareas",
    "notification-early": "Recordatorio temprano",
    "notification-early-desc": "X minutos antes de la tarea",
    "notification-ontime": "A tiempo",
    "notification-ontime-desc": "Momento exacto de la tarea",
    "notification-deadline-early": "Plazo \u2014 minutos antes",
    "notification-deadline-early-desc": "X minutos antes del plazo",
    "notification-deadline-now": "Plazo \u2014 ahora",
    "notification-deadline-now-desc": "Hora exacta del plazo",
    "notification-deadline-today": "Plazo \u2014 hoy",
    "notification-deadline-today-desc": "El plazo es hoy (sin hora)",
    "notification-deadline-days": "Plazo \u2014 d\xEDas",
    "notification-deadline-days-desc": "Faltan X d\xEDas para el plazo",
    "scan-folders": "Carpetas para escanear",
    "scan-folders-desc": "Carpetas para buscar tareas (separadas por coma)",
    "no-folders-selected": "Ninguna carpeta seleccionada (vault entero)",
    "placeholders": "Placeholders: {task} {min} {days} {time} {endTime} {file} {date}",
    "advanced-folder-mode": "Modo avanzado de selecci\xF3n de carpetas",
    "advanced-folder-mode-desc": "Use el selector avanzado con \xE1rbol de carpetas (desactive para modo simple con texto)",
    "info-title": "C\xF3mo funciona la creaci\xF3n y edici\xF3n de tareas:",
    "info-para1": "Haga clic en un espacio vac\xEDo en la cuadr\xEDcula de horas \u2014 abre el modal del plugin Tasks para crear una nueva tarea. La tarea se guarda autom\xE1ticamente en la nota diaria del d\xEDa seleccionado, usando la carpeta y formato configurados en el plugin Daily Notes (Configuraci\xF3n \u2192 Daily Notes).",
    "info-para2": "Doble clic en una tarea \u2014 abre el modal de Tasks para editar la tarea existente (fecha, hora, recurrencia, etc.). Los cambios se guardan directamente en el archivo original.",
    "info-para3": "Casilla de verificaci\xF3n \u2014 marcar o desmarcar una tarea. Si el plugin Tasks est\xE1 instalado, usa su l\xF3gica (recurrencia autom\xE1tica, fecha de finalizaci\xF3n, etc.). De lo contrario, usa la l\xF3gica interna del plugin.",
    "info-footer": "Requiere el plugin Tasks (obsidian-tasks-plugin) para crear y editar tareas. Sin \xE9l, solo funciona el toggle de la casilla de verificaci\xF3n."
  },
  "fr": {
    "view-title": "Planificateur de Blocs de Temps",
    "day-view": "Vue Journali\xE8re",
    "week-view": "Vue Hebdomadaire",
    "today": "Aujourd'hui",
    "unscheduled-tasks": "T\xE2ches sans horaire d\xE9fini",
    "no-tasks": "Aucune t\xE2che programm\xE9e",
    "create-task": "Cr\xE9er une t\xE2che",
    "hours": "Heures",
    "priority-high": "Haute",
    "priority-medium": "Moyenne",
    "priority-low": "Basse",
    "task-completed": "T\xE2che termin\xE9e",
    "task-uncompleted": "T\xE2che non termin\xE9e",
    // Dias da semana
    "sunday": "Dim",
    "monday": "Lun",
    "tuesday": "Mar",
    "wednesday": "Mer",
    "thursday": "Jeu",
    "friday": "Ven",
    "saturday": "Sam",
    // Configurações
    "settings-agenda": "Agenda",
    "settings-appearance": "Apparence",
    "settings-notifications": "Notifications",
    "settings-deadlines": "\xC9ch\xE9ances",
    "settings-texts": "Textes",
    "start-hour": "Heure de d\xE9but",
    "start-hour-desc": "Heure quand l'agenda commence",
    "end-hour": "Heure de fin",
    "end-hour-desc": "Heure quand l'agenda se termine",
    "default-view": "Vue par d\xE9faut",
    "default-view-desc": "Vue par d\xE9faut \xE0 l'ouverture de l'agenda",
    "use-obsidian-theme": "Utiliser le th\xE8me Obsidian",
    "use-obsidian-theme-desc": "Utiliser les couleurs de votre th\xE8me Obsidian actuel",
    "enable-notifications": "Activer les notifications",
    "enable-notifications-desc": "Afficher les notifications de bureau pour les t\xE2ches",
    "notification-early": "Rappel anticip\xE9",
    "notification-early-desc": "X minutes avant la t\xE2che",
    "notification-ontime": "\xC0 l'heure",
    "notification-ontime-desc": "Moment exact de la t\xE2che",
    "notification-deadline-early": "\xC9ch\xE9ance \u2014 minutes avant",
    "notification-deadline-early-desc": "X minutes avant l'\xE9ch\xE9ance",
    "notification-deadline-now": "\xC9ch\xE9ance \u2014 maintenant",
    "notification-deadline-now-desc": "Heure exacte de l'\xE9ch\xE9ance",
    "notification-deadline-today": "\xC9ch\xE9ance \u2014 aujourd'hui",
    "notification-deadline-today-desc": "L'\xE9ch\xE9ance est aujourd'hui (sans heure)",
    "notification-deadline-days": "\xC9ch\xE9ance \u2014 jours",
    "notification-deadline-days-desc": "X jours jusqu'\xE0 l'\xE9ch\xE9ance",
    "scan-folders": "Dossiers \xE0 scanner",
    "scan-folders-desc": "Dossiers pour chercher les t\xE2ches (s\xE9par\xE9s par virgule)",
    "no-folders-selected": "Aucun dossier s\xE9lectionn\xE9 (vault entier)",
    "placeholders": "Placeholders: {task} {min} {days} {time} {endTime} {file} {date}",
    "advanced-folder-mode": "Mode avanc\xE9 de s\xE9lection de dossiers",
    "advanced-folder-mode-desc": "Utilisez le s\xE9lecteur avanc\xE9 avec arborescence (d\xE9sactivez pour mode simple avec texte)",
    "info-title": "Comment fonctionne la cr\xE9ation et l'\xE9dition de t\xE2ches :",
    "info-para1": "Cliquez sur un cr\xE9neau vide dans la grille d'heures \u2014 ouvre le modal du plugin Tasks pour cr\xE9er une nouvelle t\xE2che. La t\xE2che est sauvegard\xE9e automatiquement dans la note quotidienne du jour s\xE9lectionn\xE9, en utilisant le dossier et le format configur\xE9s dans le plugin Daily Notes (Param\xE8tres \u2192 Daily Notes).",
    "info-para2": "Double-clic sur une t\xE2che \u2014 ouvre le modal Tasks pour modifier la t\xE2che existante (date, heure, r\xE9currence, etc.). Les modifications sont sauvegard\xE9es directement dans le fichier original.",
    "info-para3": "Case \xE0 cocher \u2014 marquer ou d\xE9marquer une t\xE2che. Si le plugin Tasks est install\xE9, utilise sa logique (r\xE9currence automatique, date de fin, etc.). Sinon, utilise la logique interne du plugin.",
    "info-footer": "N\xE9cessite le plugin Tasks (obsidian-tasks-plugin) pour cr\xE9er et modifier des t\xE2ches. Sans lui, seule la case \xE0 cocher fonctionne."
  },
  "de": {
    "view-title": "Block-Zeitplaner",
    "day-view": "Tagesansicht",
    "week-view": "Wochenansicht",
    "today": "Heute",
    "unscheduled-tasks": "Aufgaben ohne definierte Uhrzeit",
    "no-tasks": "Keine Aufgaben geplant",
    "create-task": "Aufgabe erstellen",
    "hours": "Stunden",
    "priority-high": "Hoch",
    "priority-medium": "Mittel",
    "priority-low": "Niedrig",
    "task-completed": "Aufgabe erledigt",
    "task-uncompleted": "Aufgabe nicht erledigt",
    // Dias da semana
    "sunday": "So",
    "monday": "Mo",
    "tuesday": "Di",
    "wednesday": "Mi",
    "thursday": "Do",
    "friday": "Fr",
    "saturday": "Sa",
    // Configurações
    "settings-agenda": "Agenda",
    "settings-appearance": "Erscheinungsbild",
    "settings-notifications": "Benachrichtigungen",
    "settings-deadlines": "Fristen",
    "settings-texts": "Texte",
    "start-hour": "Startzeit",
    "start-hour-desc": "Stunde wann die Agenda beginnt",
    "end-hour": "Endzeit",
    "end-hour-desc": "Stunde wann die Agenda endet",
    "default-view": "Standardansicht",
    "default-view-desc": "Standardansicht beim \xD6ffnen der Agenda",
    "use-obsidian-theme": "Obsidian-Theme verwenden",
    "use-obsidian-theme-desc": "Farben Ihres aktuellen Obsidian-Themes verwenden",
    "enable-notifications": "Benachrichtigungen aktivieren",
    "enable-notifications-desc": "Desktop-Benachrichtigungen f\xFCr Aufgaben anzeigen",
    "notification-early": "Fr\xFChe Erinnerung",
    "notification-early-desc": "X Minuten vor der Aufgabe",
    "notification-ontime": "P\xFCnktlich",
    "notification-ontime-desc": "Exakter Zeitpunkt der Aufgabe",
    "notification-deadline-early": "Frist \u2014 Minuten vorher",
    "notification-deadline-early-desc": "X Minuten vor der Frist",
    "notification-deadline-now": "Frist \u2014 jetzt",
    "notification-deadline-now-desc": "Exakte Fristzeit",
    "notification-deadline-today": "Frist \u2014 heute",
    "notification-deadline-today-desc": "Frist ist heute (keine Zeit)",
    "notification-deadline-days": "Frist \u2014 Tage",
    "notification-deadline-days-desc": "X Tage bis zur Frist",
    "scan-folders": "Ordner scannen",
    "scan-folders-desc": "Ordner f\xFCr Aufgaben (Komma getrennt)",
    "no-folders-selected": "Keine Ordner ausgew\xE4hlt (ganzer Vault)",
    "placeholders": "Placeholders: {task} {min} {days} {time} {endTime} {file} {date}",
    "advanced-folder-mode": "Erweiterter Ordnerauswahlmodus",
    "advanced-folder-mode-desc": "Verwenden Sie erweiterten Ordnerauswahl mit Baumansicht (deaktivieren f\xFCr einfachen Textmodus)",
    "info-title": "So funktioniert das Erstellen und Bearbeiten von Aufgaben:",
    "info-para1": "Klicken Sie auf einen leeren Zeitslot im Stundenraster \u2014 \xF6ffnet das Tasks-Plugin-Modal zum Erstellen einer neuen Aufgabe. Die Aufgabe wird automatisch in der Tagesnotiz des ausgew\xE4hlten Tages gespeichert, unter Verwendung des Ordners und Formats, das im Daily Notes-Plugin konfiguriert ist (Einstellungen \u2192 Daily Notes).",
    "info-para2": "Doppelklick auf eine Aufgabe \u2014 \xF6ffnet das Tasks-Modal zum Bearbeiten der vorhandenen Aufgabe (Datum, Uhrzeit, Wiederholung usw.). \xC4nderungen werden direkt in der Originaldatei gespeichert.",
    "info-para3": "Kontrollk\xE4stchen \u2014 Aufgabe markieren oder demarkieren. Wenn das Tasks-Plugin installiert ist, wird dessen Logik verwendet (automatische Wiederholung, Erledigungsdatum usw.). Andernfalls wird die interne Logik des Plugins verwendet.",
    "info-footer": "Erfordert das Tasks-Plugin (obsidian-tasks-plugin) zum Erstellen und Bearbeiten von Aufgaben. Ohne es funktioniert nur das Kontrollk\xE4stchen."
  },
  "it": {
    "view-title": "Programmatore di Blocchi di Tempo",
    "day-view": "Vista Giornaliera",
    "week-view": "Vista Settimanale",
    "today": "Oggi",
    "unscheduled-tasks": "Attivit\xE0 senza orario definito",
    "no-tasks": "Nessuna attivit\xE0 programmata",
    "create-task": "Crea attivit\xE0",
    "hours": "Ore",
    "priority-high": "Alta",
    "priority-medium": "Media",
    "priority-low": "Bassa",
    "task-completed": "Attivit\xE0 completata",
    "task-uncompleted": "Attivit\xE0 non completata",
    // Dias da semana
    "sunday": "Dom",
    "monday": "Lun",
    "tuesday": "Mar",
    "wednesday": "Mer",
    "thursday": "Gio",
    "friday": "Ven",
    "saturday": "Sab"
  },
  "ja": {
    "view-title": "\u30D6\u30ED\u30C3\u30AF\u30BF\u30A4\u30E0\u30B9\u30B1\u30B8\u30E5\u30FC\u30E9\u30FC",
    "day-view": "\u65E5\u8868\u793A",
    "week-view": "\u9031\u8868\u793A",
    "today": "\u4ECA\u65E5",
    "unscheduled-tasks": "\u6642\u9593\u672A\u5B9A\u306E\u30BF\u30B9\u30AF",
    "no-tasks": "\u30B9\u30B1\u30B8\u30E5\u30FC\u30EB\u3055\u308C\u305F\u30BF\u30B9\u30AF\u306F\u3042\u308A\u307E\u305B\u3093",
    "create-task": "\u30BF\u30B9\u30AF\u4F5C\u6210",
    "hours": "\u6642\u9593",
    "priority-high": "\u9AD8",
    "priority-medium": "\u4E2D",
    "priority-low": "\u4F4E",
    "task-completed": "\u30BF\u30B9\u30AF\u5B8C\u4E86",
    "task-uncompleted": "\u30BF\u30B9\u30AF\u672A\u5B8C\u4E86",
    // Dias da semana
    "sunday": "\u65E5",
    "monday": "\u6708",
    "tuesday": "\u706B",
    "wednesday": "\u6C34",
    "thursday": "\u6728",
    "friday": "\u91D1",
    "saturday": "\u571F"
  },
  "zh": {
    "view-title": "\u65F6\u95F4\u5757\u8C03\u5EA6\u5668",
    "day-view": "\u65E5\u89C6\u56FE",
    "week-view": "\u5468\u89C6\u56FE",
    "today": "\u4ECA\u5929",
    "unscheduled-tasks": "\u672A\u5B9A\u4E49\u65F6\u95F4\u7684\u4EFB\u52A1",
    "no-tasks": "\u6CA1\u6709\u5B89\u6392\u7684\u4EFB\u52A1",
    "create-task": "\u521B\u5EFA\u4EFB\u52A1",
    "hours": "\u5C0F\u65F6",
    "priority-high": "\u9AD8",
    "priority-medium": "\u4E2D",
    "priority-low": "\u4F4E",
    "task-completed": "\u4EFB\u52A1\u5DF2\u5B8C\u6210",
    "task-uncompleted": "\u4EFB\u52A1\u672A\u5B8C\u6210",
    // Dias da semana
    "sunday": "\u5468\u65E5",
    "monday": "\u5468\u4E00",
    "tuesday": "\u5468\u4E8C",
    "wednesday": "\u5468\u4E09",
    "thursday": "\u5468\u56DB",
    "friday": "\u5468\u4E94",
    "saturday": "\u5468\u516D"
  },
  "ru": {
    "view-title": "\u041F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0449\u0438\u043A \u0432\u0440\u0435\u043C\u0435\u043D\u043D\u044B\u0445 \u0431\u043B\u043E\u043A\u043E\u0432",
    "day-view": "\u0414\u043D\u0435\u0432\u043D\u043E\u0439 \u0432\u0438\u0434",
    "week-view": "\u041D\u0435\u0434\u0435\u043B\u044C\u043D\u044B\u0439 \u0432\u0438\u0434",
    "today": "\u0421\u0435\u0433\u043E\u0434\u043D\u044F",
    "unscheduled-tasks": "\u0417\u0430\u0434\u0430\u0447\u0438 \u0431\u0435\u0437 \u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0435\u043D\u043D\u043E\u0433\u043E \u0432\u0440\u0435\u043C\u0435\u043D\u0438",
    "no-tasks": "\u041D\u0435\u0442 \u0437\u0430\u043F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0445 \u0437\u0430\u0434\u0430\u0447",
    "create-task": "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0437\u0430\u0434\u0430\u0447\u0443",
    "hours": "\u0427\u0430\u0441\u044B",
    "priority-high": "\u0412\u044B\u0441\u043E\u043A\u0438\u0439",
    "priority-medium": "\u0421\u0440\u0435\u0434\u043D\u0438\u0439",
    "priority-low": "\u041D\u0438\u0437\u043A\u0438\u0439",
    "task-completed": "\u0417\u0430\u0434\u0430\u0447\u0430 \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u0430",
    "task-uncompleted": "\u0417\u0430\u0434\u0430\u0447\u0430 \u043D\u0435 \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u0430",
    // Dias da semana
    "sunday": "\u0412\u0441",
    "monday": "\u041F\u043D",
    "tuesday": "\u0412\u0442",
    "wednesday": "\u0421\u0440",
    "thursday": "\u0427\u0442",
    "friday": "\u041F\u0442",
    "saturday": "\u0421\u0431"
  }
};
var I18n = class {
  constructor() {
    this.locale = import_obsidian.moment.locale() || "en";
    const localeMap = {
      "pt-br": "pt",
      "pt": "pt",
      "es": "es",
      "fr": "fr",
      "de": "de",
      "it": "it",
      "ja": "ja",
      "zh-cn": "zh",
      "zh": "zh",
      "ru": "ru"
    };
    this.locale = localeMap[this.locale.toLowerCase()] || "en";
    this.translations = TRANSLATIONS;
  }
  t(key) {
    var _a;
    return ((_a = this.translations[this.locale]) == null ? void 0 : _a[key]) || this.translations["en"][key] || key;
  }
  getLocale() {
    return this.locale;
  }
};
function setCssProps(element, props) {
  for (const [key, value] of Object.entries(props)) {
    element.style.setProperty(key, String(value));
  }
}
var PLUGIN_VERSION = "1.0.2";
var VIEW_TYPE_BLOCK_TIME = "block-time-view";
var BlockTimeSchedulerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.notificationInterval = null;
    this.firedNotifications = /* @__PURE__ */ new Set();
    this.lastResetDate = "";
    // Índice persistente de tasks por arquivo — invalidação incremental
    this.taskIndex = /* @__PURE__ */ new Map();
    this.dirtyFiles = /* @__PURE__ */ new Set();
    this.settingTab = null;
  }
  // Referência para invalidação de cache
  async onload() {
    await this.loadSettings();
    this.i18n = new I18n();
    this.registerView(
      VIEW_TYPE_BLOCK_TIME,
      (leaf) => new BlockTimeView(leaf, this)
    );
    this.addCommand({
      id: "open-agenda",
      name: "Open agenda",
      callback: () => {
        void this.activateView("tab");
      }
    });
    this.addCommand({
      id: "open-agenda-sidebar",
      name: "Open agenda in sidebar",
      callback: () => {
        void this.activateView("sidebar");
      }
    });
    this.addRibbonIcon("calendar-clock", "Block time scheduler", () => {
      void this.activateView("tab");
    });
    this.settingTab = new BlockTimeSettingTab(this.app, this);
    this.addSettingTab(this.settingTab);
    this.registerEvent(this.app.vault.on("modify", () => {
      if (this.settingTab) {
        this.settingTab.invalidateFolderCache();
      }
    }));
    this.registerEvent(this.app.vault.on("delete", () => {
      if (this.settingTab) {
        this.settingTab.invalidateFolderCache();
      }
    }));
    this.registerEvent(this.app.vault.on("rename", () => {
      if (this.settingTab) {
        this.settingTab.invalidateFolderCache();
      }
    }));
    this.registerEvent(this.app.metadataCache.on("changed", () => {
      if (this.settingTab) {
        this.settingTab.invalidateFolderCache();
      }
    }));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile) {
          this.dirtyFiles.add(file.path);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile) {
          this.taskIndex.delete(file.path);
          this.dirtyFiles.delete(file.path);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.taskIndex.delete(oldPath);
        this.dirtyFiles.delete(oldPath);
        if (file instanceof import_obsidian.TFile) {
          this.dirtyFiles.add(file.path);
        }
      })
    );
    this.startNotificationScheduler();
    console.debug(`Block Time Scheduler v${PLUGIN_VERSION} carregado!`);
  }
  onunload() {
    this.stopNotificationScheduler();
    console.debug(`Block Time Scheduler v${PLUGIN_VERSION} descarregado!`);
  }
  getTasksApi() {
    var _a, _b, _c;
    try {
      const appWithPlugins = this.app;
      const plugin = (_b = (_a = appWithPlugins.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["obsidian-tasks-plugin"];
      return (_c = plugin == null ? void 0 : plugin.apiV1) != null ? _c : null;
    } catch (e) {
      return null;
    }
  }
  // ========================================================================
  // SISTEMA DE NOTIFICAÇÕES
  // ========================================================================
  startNotificationScheduler() {
    this.stopNotificationScheduler();
    this.firedNotifications.clear();
    this.lastResetDate = new Date().toDateString();
    this.notificationInterval = window.setInterval(() => {
      void this.checkAndFireNotifications();
    }, 6e4);
    this.registerInterval(this.notificationInterval);
    setTimeout(() => {
      void this.checkAndFireNotifications();
    }, 5e3);
  }
  stopNotificationScheduler() {
    if (this.notificationInterval) {
      clearInterval(this.notificationInterval);
      this.notificationInterval = null;
    }
  }
  async checkAndFireNotifications() {
    if (!this.settings.enableNotifications)
      return;
    const todayStr = new Date().toDateString();
    if (this.lastResetDate !== todayStr) {
      this.firedNotifications.clear();
      this.lastResetDate = todayStr;
    }
    const taskParser = new TaskParser(this.app, this.settings, this.taskIndex, this.dirtyFiles);
    const now = new Date();
    const allTasks = await taskParser.getAllTasks();
    const todayTasks = allTasks.filter((t) => t.date && taskParser.isSameDay(t.date, now));
    for (const task of todayTasks) {
      if (task.completed || !task.startTime)
        continue;
      const [taskHour, taskMin] = task.startTime.split(":").map(Number);
      const taskTime = new Date(now);
      taskTime.setHours(taskHour, taskMin, 0, 0);
      const diffMs = taskTime.getTime() - now.getTime();
      const diffMin = Math.round(diffMs / 6e4);
      if (this.settings.enableReminderBefore && this.settings.reminderMinutesBefore > 0) {
        const earlyId = `early-${task.filePath}:${task.line}-${task.startTime}`;
        if (!this.firedNotifications.has(earlyId)) {
          if (diffMin > 0 && diffMin <= this.settings.reminderMinutesBefore) {
            this.fireNotification(
              this.renderTemplate(this.settings.notifyTextEarlyTask, task, diffMin),
              `\xC0s ${task.startTime}${task.endTime ? " - " + task.endTime : ""}`,
              earlyId
            );
          }
        }
      }
      const onTimeId = `ontime-${task.filePath}:${task.line}-${task.startTime}`;
      if (!this.firedNotifications.has(onTimeId)) {
        if (diffMin <= 0 && diffMin >= -2) {
          this.fireNotification(
            this.renderTemplate(this.settings.notifyTextOnTimeTask, task),
            `Hor\xE1rio: ${task.startTime}${task.endTime ? " - " + task.endTime : ""}`,
            onTimeId
          );
        }
      }
    }
    this.checkDeadlineNotifications(allTasks, now);
  }
  checkDeadlineNotifications(allTasks, now) {
    if (!this.settings.enableDeadlineReminders)
      return;
    const tags = this.settings.deadlineTags.split(",").map((t) => t.trim().toLowerCase()).filter((t) => t.length > 0);
    if (tags.length === 0)
      return;
    for (const task of allTasks) {
      if (task.completed || !task.date)
        continue;
      const rawLower = task.rawLine.toLowerCase();
      const hasTag = tags.some((tag) => rawLower.includes(tag));
      if (!hasTag)
        continue;
      const deadlineDate = new Date(task.date);
      deadlineDate.setHours(0, 0, 0, 0);
      const today = new Date(now);
      today.setHours(0, 0, 0, 0);
      const diffDays = Math.round((deadlineDate.getTime() - today.getTime()) / 864e5);
      if (diffDays < 0)
        continue;
      if (diffDays === 0 && task.startTime) {
        const [tH, tM] = task.startTime.split(":").map(Number);
        const taskTime = new Date(now);
        taskTime.setHours(tH, tM, 0, 0);
        const diffMin = Math.round((taskTime.getTime() - now.getTime()) / 6e4);
        const earlyDeadlineId = `deadline-early-${task.filePath}:${task.line}-${task.startTime}`;
        if (!this.firedNotifications.has(earlyDeadlineId)) {
          if (diffMin > 0 && diffMin <= this.settings.reminderMinutesBefore) {
            this.fireNotification(
              this.renderTemplate(this.settings.notifyTextDeadlineEarly, task, diffMin),
              `\xC0s ${task.startTime}${task.endTime ? " - " + task.endTime : ""} \u2022 ${task.filePath.split("/").pop()}`,
              earlyDeadlineId
            );
          }
        }
        const onTimeDeadlineId = `deadline-ontime-${task.filePath}:${task.line}-${task.startTime}`;
        if (!this.firedNotifications.has(onTimeDeadlineId)) {
          if (diffMin <= 0 && diffMin >= -2) {
            this.fireNotification(
              this.renderTemplate(this.settings.notifyTextDeadlineNow, task),
              `Hor\xE1rio: ${task.startTime}${task.endTime ? " - " + task.endTime : ""} \u2022 ${task.filePath.split("/").pop()}`,
              onTimeDeadlineId
            );
          }
        }
      }
      if (diffDays === 0 && !task.startTime && now.getHours() >= this.settings.deadlineReminderHour) {
        const deadlineId = `deadline-${task.filePath}:${task.line}`;
        if (!this.firedNotifications.has(deadlineId)) {
          this.fireNotification(
            this.renderTemplate(this.settings.notifyTextDeadlineToday, task),
            `Arquivo: ${task.filePath.split("/").pop()}`,
            deadlineId
          );
        }
      }
      if (diffDays > 0 && diffDays <= this.settings.deadlineReminderDays && now.getHours() >= this.settings.deadlineReminderHour) {
        const deadlineId = `deadline-${task.filePath}:${task.line}`;
        if (!this.firedNotifications.has(deadlineId)) {
          this.fireNotification(
            this.renderTemplate(this.settings.notifyTextDeadlineDays, task, void 0, diffDays),
            `Vence em ${this.formatDateStr(deadlineDate)} \u2022 ${task.filePath.split("/").pop()}`,
            deadlineId
          );
        }
      }
    }
  }
  renderTemplate(template, task, diffMin, diffDays) {
    var _a, _b, _c;
    return template.replace(/\{task\}/g, task.text).replace(/\{min\}/g, diffMin !== void 0 ? String(diffMin) : "").replace(/\{days\}/g, diffDays !== void 0 ? String(diffDays) : "").replace(/\{time\}/g, (_a = task.startTime) != null ? _a : "").replace(/\{endTime\}/g, (_b = task.endTime) != null ? _b : "").replace(/\{file\}/g, (_c = task.filePath.split("/").pop()) != null ? _c : "").replace(/\{date\}/g, task.date ? this.formatDateStr(task.date) : "");
  }
  formatDateStr(date) {
    return `${date.getDate().toString().padStart(2, "0")}/${(date.getMonth() + 1).toString().padStart(2, "0")}`;
  }
  fireNotification(title, body, id) {
    this.firedNotifications.add(id);
    new import_obsidian.Notice(`${title}
${body}`, 1e4);
    if ("Notification" in window) {
      if (Notification.permission === "granted") {
        new Notification(title, { body });
      } else if (Notification.permission !== "denied") {
        void Notification.requestPermission().then((permission) => {
          if (permission === "granted") {
            new Notification(title, { body });
          }
        }).catch(() => {
        });
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView(mode = "tab") {
    const { workspace } = this.app;
    workspace.getLeavesOfType(VIEW_TYPE_BLOCK_TIME).forEach((l) => l.detach());
    let leaf = null;
    if (mode === "sidebar") {
      leaf = workspace.getRightLeaf(false);
    } else {
      leaf = workspace.getLeaf("tab");
    }
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_BLOCK_TIME,
        active: true
      });
      void workspace.revealLeaf(leaf);
    }
  }
};
var _TaskParser = class {
  constructor(app, settings, taskIndex, dirtyFiles) {
    // Métricas de performance
    this.filesReindexed = 0;
    this.filesSkipped = 0;
    this.app = app;
    this.settings = settings;
    this.taskIndex = taskIndex;
    this.dirtyFiles = dirtyFiles;
  }
  async readFile(file) {
    return await this.app.vault.cachedRead(file);
  }
  /** Yield ao main thread para não bloquear a UI */
  yieldToMain() {
    return new Promise((resolve) => setTimeout(resolve, 0));
  }
  /** Early-exit: verifica rapidamente se conteúdo pode ter tasks */
  hasTaskPatternQuick(content) {
    return _TaskParser.TASK_PATTERN.test(content);
  }
  /** Processa um batch de arquivos em paralelo */
  async processFileBatch(files) {
    const results = await Promise.allSettled(
      files.map(async (file) => {
        const content = await this.readFile(file);
        if (!this.hasTaskPatternQuick(content)) {
          this.filesSkipped++;
          this.taskIndex.set(file.path, []);
          return;
        }
        const tasks = [];
        const lines = content.split("\n");
        for (let i = 0; i < lines.length; i++) {
          const task = this.parseLine(lines[i], file.path, i + 1);
          if (task)
            tasks.push(task);
        }
        this.taskIndex.set(file.path, tasks);
        this.filesReindexed++;
      })
    );
    for (const result of results) {
      if (result.status === "rejected") {
        console.warn("[BlockTime] Erro ao processar arquivo:", result.reason);
      }
    }
  }
  async getAllTasks() {
    const perfStart = performance.now();
    this.filesReindexed = 0;
    this.filesSkipped = 0;
    const allFiles = this.app.vault.getMarkdownFiles();
    const scanFolders = this.settings.scanFolders.split(",").map((f) => f.trim().replace(/^\/+|\/+$/g, "")).filter((f) => f.length > 0);
    const files = scanFolders.length > 0 ? allFiles.filter((f) => scanFolders.some((folder) => f.path.startsWith(folder + "/") || f.path === folder)) : allFiles;
    if (this.taskIndex.size === 0) {
      for (let i = 0; i < files.length; i += _TaskParser.BATCH_SIZE) {
        const batch = files.slice(i, i + _TaskParser.BATCH_SIZE);
        await this.processFileBatch(batch);
        if (i > 0 && i % _TaskParser.YIELD_EVERY === 0) {
          await this.yieldToMain();
        }
      }
    } else {
      const filesToReindex = files.filter((f) => this.dirtyFiles.has(f.path));
      if (filesToReindex.length > 0) {
        for (let i = 0; i < filesToReindex.length; i += _TaskParser.BATCH_SIZE) {
          const batch = filesToReindex.slice(i, i + _TaskParser.BATCH_SIZE);
          await this.processFileBatch(batch);
        }
      }
      const currentPaths = new Set(files.map((f) => f.path));
      for (const indexedPath of this.taskIndex.keys()) {
        if (!currentPaths.has(indexedPath)) {
          this.taskIndex.delete(indexedPath);
        }
      }
    }
    this.dirtyFiles.clear();
    const tasks = [];
    for (const fileTasks of this.taskIndex.values()) {
      for (const task of fileTasks) {
        tasks.push(task);
      }
    }
    const perfEnd = performance.now();
    const totalFiles = files.length;
    const indexedCount = this.taskIndex.size;
    console.debug(
      `[BlockTime] Scan: ${(perfEnd - perfStart).toFixed(1)}ms | ${totalFiles} arquivos | ${indexedCount} indexados | ${this.filesReindexed} re-parsed | ${this.filesSkipped} skipped | ${tasks.length} tasks`
    );
    const today = new Date();
    return tasks.filter((task) => {
      if (task.completed || !task.recurrence || this.hasExplicitDate(task.rawLine))
        return true;
      const hasDoneToday = tasks.some((other) => {
        if (!other.completed || !other.recurrence)
          return false;
        if (other.filePath !== task.filePath || other.text !== task.text)
          return false;
        if (this.hasExplicitDate(other.rawLine))
          return false;
        const doneDate = this.parseDoneDate(other.rawLine);
        return doneDate !== null && this.isSameDay(doneDate, today);
      });
      if (hasDoneToday) {
        const hasPending = tasks.some(
          (other) => !other.completed && other.recurrence && other.filePath === task.filePath && other.text === task.text && !this.hasExplicitDate(other.rawLine)
        );
        return hasPending;
      }
      return true;
    });
  }
  async getTasksForDate(targetDate) {
    const allTasks = await this.getAllTasks();
    return this.filterTasksForDate(allTasks, targetDate);
  }
  /** Filtra tasks para uma data específica a partir de lista pré-carregada (sem re-scan) */
  filterTasksForDate(allTasks, targetDate) {
    const tasks = [];
    const seenTaskKeys = /* @__PURE__ */ new Set();
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    for (const task of allTasks) {
      const hasExplicitDate = task.date && this.isSameDay(task.date, targetDate);
      const parsedDoneDate = this.parseDoneDate(task.rawLine);
      const hasDoneDate = parsedDoneDate !== null && this.isSameDay(parsedDoneDate, targetDate);
      if (hasExplicitDate || hasDoneDate) {
        const taskKey = `${task.rawLine.trim()}_${task.filePath}`;
        tasks.push(task);
        seenTaskKeys.add(taskKey);
      }
    }
    const targetDateStr = this.formatDate(targetDate);
    for (const task of allTasks) {
      if (!task.recurrence)
        continue;
      const baseTaskText = task.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
      const taskKey = `${baseTaskText}_${task.filePath}`;
      if (seenTaskKeys.has(taskKey))
        continue;
      const hasPendingTask = allTasks.some(
        (t) => !t.completed && t.recurrence && t.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim() === baseTaskText
      );
      if (this.shouldRecurOnDate(task, targetDate)) {
        const completedVersion = this.findCompletedTaskFromIndex(allTasks, task, targetDateStr);
        if (completedVersion) {
          tasks.push(completedVersion);
          seenTaskKeys.add(taskKey);
        } else if (hasPendingTask && (targetDate >= today || !this.hasExplicitDate(task.rawLine))) {
          const generatedTask = this.createRecurrenceInstance(task, targetDate);
          tasks.push(generatedTask);
          seenTaskKeys.add(taskKey);
        }
      }
    }
    return tasks;
  }
  /** Busca task completada diretamente no índice em memória (O(n) no arquivo, sem I/O) */
  findCompletedTaskFromIndex(allTasks, task, targetDateStr) {
    const originalText = task.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
    for (const other of allTasks) {
      if (!other.completed || other.filePath !== task.filePath)
        continue;
      const otherText = other.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
      if (originalText === otherText) {
        const doneDateMatch = other.rawLine.match(/✅\s*(\d{4}-\d{2}-\d{2})/);
        if (doneDateMatch && doneDateMatch[1] === targetDateStr) {
          return other;
        }
      }
    }
    return null;
  }
  calculateImplicitStartDate(recurrence, currentDate) {
    const rule = recurrence.toLowerCase().trim();
    const simpleWeekOnMatch = rule.match(/every\s+week\s+on\s+(.+)/i);
    if (simpleWeekOnMatch) {
      const dayText = simpleWeekOnMatch[1].toLowerCase().trim();
      const dayNames = {
        sunday: 0,
        monday: 1,
        tuesday: 2,
        wednesday: 3,
        thursday: 4,
        friday: 5,
        saturday: 6
      };
      const targetDay = dayNames[dayText];
      if (targetDay !== void 0) {
        const result = new Date(currentDate);
        const currentDay = result.getDay();
        const daysUntilTarget = (targetDay - currentDay + 7) % 7;
        result.setDate(result.getDate() + daysUntilTarget);
        return result;
      }
    }
    if (/every\s+weekday/i.test(rule)) {
      const result = new Date(currentDate);
      const currentDay = result.getDay();
      if (currentDay === 0) {
        result.setDate(result.getDate() + 1);
      } else if (currentDay === 6) {
        result.setDate(result.getDate() + 2);
      }
      return result;
    }
    return new Date(currentDate);
  }
  shouldRecurOnDate(task, targetDate) {
    if (!task.recurrence)
      return false;
    const recurrenceRule = task.recurrence.toLowerCase().trim();
    let startDate = task.date;
    if (!startDate) {
      startDate = this.calculateImplicitStartDate(task.recurrence, new Date());
    }
    if (targetDate < startDate)
      return false;
    if (/every\s+day/i.test(recurrenceRule))
      return true;
    if (/every\s+weekday/i.test(recurrenceRule)) {
      const dayOfWeek = targetDate.getDay();
      return dayOfWeek >= 1 && dayOfWeek <= 5;
    }
    const weekOnMatch = recurrenceRule.match(/every\s+(\d+)\s+weeks?\s+on\s+(.+)/i);
    if (weekOnMatch) {
      const daysText = weekOnMatch[2].toLowerCase();
      const days = daysText.split(",").map((d) => d.trim().replace(/,$/, ""));
      const dayNames = {
        sunday: 0,
        monday: 1,
        tuesday: 2,
        wednesday: 3,
        thursday: 4,
        friday: 5,
        saturday: 6
      };
      const targetDayOfWeek = targetDate.getDay();
      return days.some((day) => {
        const dayNum = dayNames[day];
        return dayNum !== void 0 && dayNum === targetDayOfWeek;
      });
    }
    const simpleWeekOnMatch = recurrenceRule.match(/every\s+week\s+on\s+(.+)/i);
    if (simpleWeekOnMatch) {
      const dayText = simpleWeekOnMatch[1].toLowerCase().trim();
      const dayNames = {
        sunday: 0,
        monday: 1,
        tuesday: 2,
        wednesday: 3,
        thursday: 4,
        friday: 5,
        saturday: 6
      };
      const targetDayOfWeek = targetDate.getDay();
      const dayNum = dayNames[dayText];
      return dayNum !== void 0 && dayNum === targetDayOfWeek;
    }
    if (/every\s+week$/i.test(recurrenceRule)) {
      return startDate.getDay() === targetDate.getDay();
    }
    const monthOnMatch = recurrenceRule.match(/every\s+month\s+on\s+the\s+(\d+)(?:st|nd|rd|th)/i);
    if (monthOnMatch) {
      const targetDay = parseInt(monthOnMatch[1]);
      return targetDate.getDate() === targetDay;
    }
    const nMonthOnMatch = recurrenceRule.match(/every\s+(\d+)\s+months?\s+on\s+the\s+(\d+)(?:st|nd|rd|th)/i);
    if (nMonthOnMatch) {
      const n = parseInt(nMonthOnMatch[1]);
      const targetDay = parseInt(nMonthOnMatch[2]);
      const monthsDiff = (targetDate.getFullYear() - startDate.getFullYear()) * 12 + (targetDate.getMonth() - startDate.getMonth());
      return monthsDiff >= 0 && monthsDiff % n === 0 && targetDate.getDate() === targetDay;
    }
    const nMonthWeekdayMatch = recurrenceRule.match(/every\s+(\d+)\s+months?\s+on\s+the\s+(\d+)(?:st|nd|rd|th)\s+(sunday|monday|tuesday|wednesday|thursday|friday|saturday)/i);
    if (nMonthWeekdayMatch) {
      const n = parseInt(nMonthWeekdayMatch[1]);
      const weekNum = parseInt(nMonthWeekdayMatch[2]);
      const weekday = nMonthWeekdayMatch[3].toLowerCase();
      const dayNames = {
        sunday: 0,
        monday: 1,
        tuesday: 2,
        wednesday: 3,
        thursday: 4,
        friday: 5,
        saturday: 6
      };
      const targetWeekday = dayNames[weekday];
      const firstDayOfMonth = new Date(targetDate.getFullYear(), targetDate.getMonth(), 1);
      const firstWeekday = firstDayOfMonth.getDay();
      const offset = (targetWeekday - firstWeekday + 7) % 7;
      const targetDateOfMonth = 1 + offset + (weekNum - 1) * 7;
      if (targetDateOfMonth > new Date(targetDate.getFullYear(), targetDate.getMonth() + 1, 0).getDate()) {
        return false;
      }
      const monthsDiff = (targetDate.getFullYear() - startDate.getFullYear()) * 12 + (targetDate.getMonth() - startDate.getMonth());
      return monthsDiff >= 0 && monthsDiff % n === 0 && targetDate.getDate() === targetDateOfMonth;
    }
    const specificMonthMatch = recurrenceRule.match(/every\s+(january|february|march|april|may|june|july|august|september|october|november|december)\s+on\s+the\s+(\d+)(?:st|nd|rd|th)/i);
    if (specificMonthMatch) {
      const monthName = specificMonthMatch[1].toLowerCase();
      const targetDay = parseInt(specificMonthMatch[2]);
      const monthNames = {
        january: 0,
        february: 1,
        march: 2,
        april: 3,
        may: 4,
        june: 5,
        july: 6,
        august: 7,
        september: 8,
        october: 9,
        november: 10,
        december: 11
      };
      return targetDate.getMonth() === monthNames[monthName] && targetDate.getDate() === targetDay;
    }
    const specificMonthsMatch = recurrenceRule.match(/every\s+(january|february|march|april|may|june|july|august|september|october|november|december)\s+and\s+(january|february|march|april|may|june|july|august|september|october|november|december)\s+on\s+the\s+(\d+)(?:st|nd|rd|th)\s+and\s+the\s+(\d+)(?:st|nd|rd|th)/i);
    if (specificMonthsMatch) {
      const month1Name = specificMonthsMatch[1].toLowerCase();
      const month2Name = specificMonthsMatch[2].toLowerCase();
      const targetDay1 = parseInt(specificMonthsMatch[3]);
      const targetDay2 = parseInt(specificMonthsMatch[4]);
      const monthNames = {
        january: 0,
        february: 1,
        march: 2,
        april: 3,
        may: 4,
        june: 5,
        july: 6,
        august: 7,
        september: 8,
        october: 9,
        november: 10,
        december: 11
      };
      const currentMonth = targetDate.getMonth();
      const currentDay = targetDate.getDate();
      return currentMonth === monthNames[month1Name] && currentDay === targetDay1 || currentMonth === monthNames[month2Name] && currentDay === targetDay2;
    }
    if (/every\s+month/i.test(recurrenceRule)) {
      return startDate.getDate() === targetDate.getDate();
    }
    const nMatch = recurrenceRule.match(/every\s+(\d+)\s+(day|week|month|year)s?/i);
    if (nMatch) {
      const n = parseInt(nMatch[1]);
      const unit = nMatch[2].toLowerCase();
      const diffDays = Math.floor((targetDate.getTime() - startDate.getTime()) / (1e3 * 60 * 60 * 24));
      if (unit === "day" && diffDays >= 0 && diffDays % n === 0)
        return true;
      if (unit === "week" && diffDays >= 0 && diffDays % (n * 7) === 0)
        return true;
      if (unit === "month") {
        const monthsDiff = (targetDate.getFullYear() - startDate.getFullYear()) * 12 + (targetDate.getMonth() - startDate.getMonth());
        return monthsDiff >= 0 && monthsDiff % n === 0 && targetDate.getDate() === startDate.getDate();
      }
      if (unit === "year") {
        const yearsDiff = targetDate.getFullYear() - startDate.getFullYear();
        return yearsDiff >= 0 && yearsDiff % n === 0 && targetDate.getMonth() === startDate.getMonth() && targetDate.getDate() === startDate.getDate();
      }
    }
    return false;
  }
  async findCompletedTask(task, targetDate) {
    try {
      const file = this.app.vault.getAbstractFileByPath(task.filePath);
      if (!(file instanceof import_obsidian.TFile))
        return null;
      const content = await this.readFile(file);
      const lines = content.split("\n");
      const targetDateStr = this.formatDate(targetDate);
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const taskMatch = line.match(/^(\s*)-\s*\[x\]\s*(.*)$/);
        if (!taskMatch)
          continue;
        const completedTaskText = taskMatch[2];
        const originalText = task.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
        const completedText = completedTaskText.replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
        if (originalText === completedText) {
          const doneDateMatch = line.match(/✅\s*(\d{4}-\d{2}-\d{2})/);
          if (doneDateMatch && doneDateMatch[1] === targetDateStr) {
            return this.parseLine(line, task.filePath, i + 1);
          }
        }
      }
      return null;
    } catch (error) {
      console.warn("[BlockTime] Erro ao buscar tarefa completada:", error);
      return null;
    }
  }
  createRecurrenceInstance(task, targetDate) {
    return {
      ...task,
      date: new Date(targetDate),
      completed: false,
      line: -1
      // Indica que é gerada
    };
  }
  async getTasksForWeek(startDate) {
    const allTasks = await this.getAllTasks();
    const tasks = [];
    const seenTaskKeys = /* @__PURE__ */ new Set();
    for (let dayOffset = 0; dayOffset < 7; dayOffset++) {
      const currentDay = new Date(startDate);
      currentDay.setDate(startDate.getDate() + dayOffset);
      const dayTasks = this.filterTasksForDate(allTasks, currentDay);
      for (const task of dayTasks) {
        const taskKey = `${task.text.trim()}_${task.filePath}_${currentDay.toDateString()}`;
        if (!seenTaskKeys.has(taskKey)) {
          tasks.push(task);
          seenTaskKeys.add(taskKey);
        }
      }
    }
    return tasks;
  }
  parseLine(line, filePath, lineNumber) {
    const taskMatch = line.match(/^(\s*)-\s*\[([ xX])\]\s*(.*)$/);
    if (!taskMatch)
      return null;
    const completed = taskMatch[2].toLowerCase() === "x";
    let taskText = taskMatch[3];
    const dateInfo = this.parseDate(taskText);
    const timeInfo = this.parseTime(taskText);
    const priority = this.parsePriority(taskText);
    const recurrence = this.parseRecurrence(taskText);
    let taskDate = dateInfo.date;
    if (!taskDate && recurrence && !completed) {
      taskDate = new Date();
    } else if (!taskDate && recurrence && completed) {
      const doneDate = this.parseDoneDate(line);
      taskDate = doneDate;
    }
    taskText = this.cleanTaskText(taskText);
    return {
      text: taskText,
      date: taskDate,
      startTime: timeInfo.startTime,
      endTime: timeInfo.endTime,
      duration: timeInfo.duration,
      completed,
      filePath,
      line: lineNumber,
      priority,
      rawLine: line,
      recurrence
    };
  }
  parseDate(text) {
    const patterns = [
      /📅\s*(\d{4}-\d{2}-\d{2})/,
      // Emoji de calendário
      /🗓️\s*(\d{4}-\d{2}-\d{2})/,
      // Emoji alternativo
      /\[due::\s*(\d{4}-\d{2}-\d{2})\]/,
      // Formato Dataview
      /due::\s*(\d{4}-\d{2}-\d{2})/,
      // Dataview inline
      /@(\d{4}-\d{2}-\d{2})/,
      // Formato @date
      /\((\d{4}-\d{2}-\d{2})\)/,
      // Entre parênteses
      /scheduled::\s*(\d{4}-\d{2}-\d{2})/,
      // Scheduled
      /⏳\s*(\d{4}-\d{2}-\d{2})/
      // Emoji de ampulheta (scheduled)
    ];
    for (const pattern of patterns) {
      const match = text.match(pattern);
      if (match) {
        const date = new Date(match[1] + "T00:00:00");
        if (!isNaN(date.getTime())) {
          return { date };
        }
      }
    }
    if (/\bhoje\b/i.test(text)) {
      return { date: new Date() };
    }
    if (/\bamanhã\b/i.test(text)) {
      const tomorrow = new Date();
      tomorrow.setDate(tomorrow.getDate() + 1);
      return { date: tomorrow };
    }
    return { date: null };
  }
  parseTime(text) {
    let startTime = null;
    let endTime = null;
    let duration = 60;
    const rangePatterns = [
      /(\d{1,2}):(\d{2})\s*[-–—]\s*(\d{1,2}):(\d{2})/,
      /(\d{1,2}):(\d{2})\s+às\s+(\d{1,2}):(\d{2})/i,
      /(\d{1,2})h(\d{2})?\s*[-–—]\s*(\d{1,2})h(\d{2})?/
    ];
    for (const pattern of rangePatterns) {
      const match = text.match(pattern);
      if (match) {
        const startHour = parseInt(match[1]);
        const startMin = parseInt(match[2] || "0");
        const endHour = parseInt(match[3]);
        const endMin = parseInt(match[4] || "0");
        startTime = `${startHour.toString().padStart(2, "0")}:${startMin.toString().padStart(2, "0")}`;
        endTime = `${endHour.toString().padStart(2, "0")}:${endMin.toString().padStart(2, "0")}`;
        duration = endHour * 60 + endMin - (startHour * 60 + startMin);
        if (duration < 0)
          duration += 24 * 60;
        return { startTime, endTime, duration };
      }
    }
    const simplePatterns = [
      /⏰\s*(\d{1,2}):(\d{2})/,
      /🕐\s*(\d{1,2}):(\d{2})/,
      /\[time::\s*(\d{1,2}):(\d{2})\]/,
      /(\d{1,2})h(\d{2})?(?!\d)/,
      /(?:^|\s)(\d{1,2}):(\d{2})(?!\d)/
    ];
    for (const pattern of simplePatterns) {
      const match = text.match(pattern);
      if (match) {
        const hour = parseInt(match[1]);
        const min = parseInt(match[2] || "0");
        startTime = `${hour.toString().padStart(2, "0")}:${min.toString().padStart(2, "0")}`;
        return { startTime, endTime, duration };
      }
    }
    return { startTime, endTime, duration };
  }
  parsePriority(text) {
    if (/🔺|⏫|!!!/i.test(text) || /\[priority::\s*high\]/i.test(text))
      return "high";
    if (/🔼|!!/i.test(text) || /\[priority::\s*medium\]/i.test(text))
      return "medium";
    if (/🔽|!/i.test(text) || /\[priority::\s*low\]/i.test(text))
      return "low";
    return "none";
  }
  cleanTaskText(text) {
    return text.replace(/📅\s*\d{4}-\d{2}-\d{2}/g, "").replace(/🗓️\s*\d{4}-\d{2}-\d{2}/g, "").replace(/⏳\s*\d{4}-\d{2}-\d{2}/g, "").replace(/⏰\s*\d{1,2}:\d{2}/g, "").replace(/🕐\s*\d{1,2}:\d{2}/g, "").replace(/\[due::\s*\d{4}-\d{2}-\d{2}\]/g, "").replace(/\[time::\s*\d{1,2}:\d{2}\]/g, "").replace(/\[priority::\s*\w+\]/g, "").replace(/due::\s*\d{4}-\d{2}-\d{2}/g, "").replace(/scheduled::\s*\d{4}-\d{2}-\d{2}/g, "").replace(/@\d{4}-\d{2}-\d{2}/g, "").replace(/🔺|⏫|🔼|🔽/g, "").replace(/✅\s*\d{4}-\d{2}-\d{2}/g, "").replace(/🔁\s*(.+?)(?=\s*(?:📅|🗓️|⏳|⏰|🕐|🔺|⏫|🔼|🔽|✅|$))/gu, "").replace(/\d{1,2}:\d{2}\s*[-–—]\s*\d{1,2}:\d{2}/g, "").replace(/\d{1,2}h\d{2}?\s*[-–—]\s*\d{1,2}h\d{2}?/g, "").replace(/\s+/g, " ").trim();
  }
  parseDoneDate(text) {
    const match = text.match(/✅\s*(\d{4}-\d{2}-\d{2})/);
    if (!match)
      return null;
    const date = new Date(match[1] + "T00:00:00");
    return isNaN(date.getTime()) ? null : date;
  }
  hasExplicitDate(line) {
    const datePatterns = [
      /📅\s*\d{4}-\d{2}-\d{2}/,
      /🗓️\s*\d{4}-\d{2}-\d{2}/,
      /\[due::\s*\d{4}-\d{2}-\d{2}\]/,
      /due::\s*\d{4}-\d{2}-\d{2}/,
      /@\d{4}-\d{2}-\d{2}/,
      /\(\d{4}-\d{2}-\d{2}\)/,
      /scheduled::\s*\d{4}-\d{2}-\d{2}/,
      /⏳\s*\d{4}-\d{2}-\d{2}/
    ];
    return datePatterns.some((p) => p.test(line));
  }
  parseRecurrence(text) {
    const match = text.match(/🔁\s*(.+?)(?=\s*(?:📅|🗓️|⏳|⏰|🕐|🔺|⏫|🔼|🔽|✅|$))/u);
    if (!match)
      return null;
    return match[1].trim();
  }
  calculateNextDate(currentDate, recurrenceText, completionDate) {
    const text = recurrenceText.toLowerCase().trim();
    const whenDone = text.includes("when done");
    const rule = text.replace(/when done/i, "").trim();
    const baseDate = whenDone ? new Date(completionDate) : new Date(currentDate);
    const nMatch = rule.match(/every\s+(\d+)\s+(day|week|month|year)s?/i);
    if (nMatch) {
      const n = parseInt(nMatch[1]);
      const unit = nMatch[2].toLowerCase();
      if (unit === "day")
        baseDate.setDate(baseDate.getDate() + n);
      else if (unit === "week")
        baseDate.setDate(baseDate.getDate() + n * 7);
      else if (unit === "month")
        baseDate.setMonth(baseDate.getMonth() + n);
      else if (unit === "year")
        baseDate.setFullYear(baseDate.getFullYear() + n);
      return baseDate;
    }
    if (/every\s+day/i.test(rule)) {
      baseDate.setDate(baseDate.getDate() + 1);
      return baseDate;
    }
    if (/every\s+week$/i.test(rule)) {
      baseDate.setDate(baseDate.getDate() + 7);
      return baseDate;
    }
    if (/every\s+month/i.test(rule)) {
      baseDate.setMonth(baseDate.getMonth() + 1);
      return baseDate;
    }
    if (/every\s+year/i.test(rule)) {
      baseDate.setFullYear(baseDate.getFullYear() + 1);
      return baseDate;
    }
    if (/every\s+weekday/i.test(rule)) {
      do {
        baseDate.setDate(baseDate.getDate() + 1);
      } while (baseDate.getDay() === 0 || baseDate.getDay() === 6);
      return baseDate;
    }
    const weekOnMatch = rule.match(/every\s+(\d+)\s+weeks?\s+on\s+(.+)/i);
    if (weekOnMatch) {
      const n = parseInt(weekOnMatch[1]);
      baseDate.setDate(baseDate.getDate() + 7 * n);
      return baseDate;
    }
    const simpleWeekOnMatch = rule.match(/every\s+week\s+on\s+(.+)/i);
    if (simpleWeekOnMatch) {
      baseDate.setDate(baseDate.getDate() + 7);
      return baseDate;
    }
    baseDate.setDate(baseDate.getDate() + 1);
    return baseDate;
  }
  formatDate(date) {
    const y = date.getFullYear();
    const m = (date.getMonth() + 1).toString().padStart(2, "0");
    const d = date.getDate().toString().padStart(2, "0");
    return `${y}-${m}-${d}`;
  }
  async toggleTaskCompletion(task, tasksApi) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!(file instanceof import_obsidian.TFile))
      return false;
    if (tasksApi) {
      try {
        const content2 = await this.app.vault.read(file);
        const lines2 = content2.split("\n");
        const lineIndex2 = task.line - 1;
        if (lineIndex2 < 0 || lineIndex2 >= lines2.length)
          return false;
        const originalLine = lines2[lineIndex2];
        const toggledLine = tasksApi.executeToggleTaskDoneCommand(originalLine, task.filePath);
        if (toggledLine && toggledLine !== originalLine) {
          lines2[lineIndex2] = toggledLine;
          await this.app.vault.modify(file, lines2.join("\n"));
          task.completed = !task.completed;
          return true;
        }
      } catch (e) {
        console.warn("[BlockTime] Tasks API toggle falhou, usando fallback manual:", e);
      }
    }
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const lineIndex = task.line - 1;
    if (lineIndex < 0 || lineIndex >= lines.length)
      return false;
    const line = lines[lineIndex];
    if (task.completed) {
      const newLine = line.replace(/- \[[xX]\]/, "- [ ]").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "");
      if (newLine === line)
        return false;
      lines[lineIndex] = newLine;
    } else {
      const todayStr = this.formatDate(new Date());
      let completedLine = line.replace(/- \[ \]/, "- [x]");
      if (!/✅/.test(completedLine)) {
        completedLine = completedLine.trimEnd() + ` \u2705 ${todayStr}`;
      }
      if (completedLine === line)
        return false;
      if (task.recurrence) {
        let newTaskLine = line.replace(/- \[ \]/, "- [ ]").replace(/✅\s*\d{4}-\d{2}-\d{2}/g, "");
        if (this.hasExplicitDate(line) && task.date) {
          const nextDate = this.calculateNextDate(task.date, task.recurrence, new Date());
          const nextDateStr = this.formatDate(nextDate);
          newTaskLine = newTaskLine.replace(/(📅\s*)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(🗓️\s*)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(⏳\s*)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(\[due::\s*)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(due::\s*)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(scheduled::\s*)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(@)\d{4}-\d{2}-\d{2}/, `$1${nextDateStr}`).replace(/(\()\d{4}-\d{2}-\d{2}(\))/, `$1${nextDateStr}$2`);
        }
        lines.splice(lineIndex, 1, newTaskLine, completedLine);
      } else {
        lines[lineIndex] = completedLine;
      }
    }
    await this.app.vault.modify(file, lines.join("\n"));
    task.completed = !task.completed;
    return true;
  }
  async editTaskLine(task, tasksApi) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!(file instanceof import_obsidian.TFile))
      return false;
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const lineIndex = task.line - 1;
    if (lineIndex < 0 || lineIndex >= lines.length)
      return false;
    const originalLine = lines[lineIndex];
    const editedLine = await tasksApi.editTaskLineModal(originalLine);
    if (editedLine && editedLine !== originalLine) {
      lines[lineIndex] = editedLine;
      await this.app.vault.modify(file, lines.join("\n"));
      return true;
    }
    return false;
  }
  isSameDay(date1, date2) {
    return date1.getFullYear() === date2.getFullYear() && date1.getMonth() === date2.getMonth() && date1.getDate() === date2.getDate();
  }
};
var TaskParser = _TaskParser;
// Constantes de otimização
TaskParser.BATCH_SIZE = 50;
TaskParser.YIELD_EVERY = 200;
// Regex rápido para early-exit: verifica se arquivo pode ter tasks
TaskParser.TASK_PATTERN = /^\s*-\s*\[[ xX]\]/m;
var BlockTimeView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.renderTimeout = null;
    this.isToggling = false;
    this.isRendering = false;
    this.dayCheckInterval = null;
    this.lastKnownDay = "";
    this.plugin = plugin;
    this.taskParser = new TaskParser(this.app, plugin.settings, plugin.taskIndex, plugin.dirtyFiles);
    this.currentDate = new Date();
    this.viewMode = plugin.settings.defaultView;
  }
  getViewType() {
    return VIEW_TYPE_BLOCK_TIME;
  }
  getDisplayText() {
    return this.plugin.i18n.t("view-title");
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    this.currentDate = new Date();
    this.lastKnownDay = new Date().toDateString();
    await this.render();
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.isToggling)
          return;
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.debouncedRender();
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (this.isToggling)
          return;
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.debouncedRender();
        }
      })
    );
    this.dayCheckInterval = window.setInterval(() => {
      this.checkDayChange();
    }, 6e4);
    this.registerInterval(this.dayCheckInterval);
    this.registerDomEvent(document, "visibilitychange", () => {
      if (document.visibilityState === "visible") {
        this.checkDayChange();
      }
    });
  }
  onClose() {
    if (this.renderTimeout)
      clearTimeout(this.renderTimeout);
    this.contentEl.empty();
    return Promise.resolve();
  }
  checkDayChange() {
    const today = new Date().toDateString();
    if (today !== this.lastKnownDay) {
      this.lastKnownDay = today;
      this.currentDate = new Date();
      void this.render();
    }
  }
  navigateDate(delta) {
    if (this.viewMode === "day") {
      this.currentDate.setDate(this.currentDate.getDate() + delta);
    } else {
      this.currentDate.setDate(this.currentDate.getDate() + delta * 7);
    }
    void this.render();
  }
  debouncedRender() {
    if (this.renderTimeout)
      clearTimeout(this.renderTimeout);
    this.renderTimeout = setTimeout(() => {
      void this.render();
    }, 800);
  }
  async render() {
    if (this.isRendering)
      return;
    this.isRendering = true;
    try {
      const container = this.contentEl;
      container.empty();
      container.addClass("block-time-container");
      if (this.plugin.settings.useObsidianTheme) {
        container.addClass("block-time-themed");
      } else {
        container.removeClass("block-time-themed");
      }
      this.renderHeader(container);
      if (this.viewMode === "day") {
        await this.renderDayView(container);
      } else {
        await this.renderWeekView(container);
      }
    } finally {
      this.isRendering = false;
    }
  }
  renderHeader(container) {
    const header = container.createDiv({ cls: "block-time-header" });
    const nav = header.createDiv({ cls: "block-time-nav" });
    const prevBtn = nav.createEl("button", { text: "\u25C0", cls: "block-time-nav-btn" });
    prevBtn.addEventListener("click", () => this.navigateDate(-1));
    const dateDisplay = nav.createDiv({ cls: "block-time-date-display" });
    this.updateDateDisplay(dateDisplay);
    const nextBtn = nav.createEl("button", { text: "\u25B6", cls: "block-time-nav-btn" });
    nextBtn.addEventListener("click", () => this.navigateDate(1));
    const todayBtn = nav.createEl("button", { text: this.plugin.i18n.t("today"), cls: "block-time-today-btn" });
    todayBtn.addEventListener("click", () => {
      this.currentDate = new Date();
      void this.render();
    });
    const controls = header.createDiv({ cls: "block-time-controls" });
    const viewToggle = controls.createDiv({ cls: "block-time-view-toggle" });
    const dayBtn = viewToggle.createEl("button", {
      text: this.plugin.i18n.t("day-view"),
      cls: `block-time-toggle-btn ${this.viewMode === "day" ? "active" : ""}`
    });
    dayBtn.addEventListener("click", () => {
      this.viewMode = "day";
      void this.render();
    });
    const weekBtn = viewToggle.createEl("button", {
      text: this.plugin.i18n.t("week-view"),
      cls: `block-time-toggle-btn ${this.viewMode === "week" ? "active" : ""}`
    });
    weekBtn.addEventListener("click", () => {
      this.viewMode = "week";
      void this.render();
    });
    const refreshBtn = controls.createEl("button", { text: "\u{1F504}", cls: "block-time-refresh-btn" });
    refreshBtn.addEventListener("click", () => {
      void this.render();
    });
  }
  updateDateDisplay(element) {
    const dayNames = [
      this.plugin.i18n.t("sunday"),
      this.plugin.i18n.t("monday"),
      this.plugin.i18n.t("tuesday"),
      this.plugin.i18n.t("wednesday"),
      this.plugin.i18n.t("thursday"),
      this.plugin.i18n.t("friday"),
      this.plugin.i18n.t("saturday")
    ];
    const dayName = dayNames[this.currentDate.getDay()];
    const date = this.currentDate.getDate();
    const month = this.currentDate.toLocaleDateString(this.plugin.i18n.getLocale(), { month: "long" });
    const year = this.currentDate.getFullYear();
    element.textContent = `${dayName}, ${date} de ${month} de ${year}`;
  }
  async renderDayView(container) {
    const grid = container.createDiv({ cls: "block-time-grid day-view" });
    const { startHour, endHour } = this.plugin.settings;
    const tasks = await this.taskParser.getTasksForDate(this.currentDate);
    const hoursColumn = grid.createDiv({ cls: "block-time-hours-column" });
    for (let hour = startHour; hour <= endHour; hour++) {
      const hourSlot = hoursColumn.createDiv({ cls: "block-time-hour-label" });
      hourSlot.textContent = `${hour.toString().padStart(2, "0")}:00`;
    }
    const tasksColumn = grid.createDiv({ cls: "block-time-tasks-column" });
    for (let hour = startHour; hour <= endHour; hour++) {
      const hourSlot = tasksColumn.createDiv({ cls: "block-time-hour-slot" });
      hourSlot.dataset.hour = hour.toString();
      this.addSlotCreateHandler(hourSlot, hour, this.currentDate);
    }
    for (const task of tasks) {
      if (task.startTime) {
        this.renderTaskBlock(tasksColumn, task, startHour);
      }
    }
    const unscheduledTasks = tasks.filter((t) => !t.startTime);
    const uniqueUnscheduledTasks = [];
    const seenRecurrenceKeys = /* @__PURE__ */ new Set();
    for (const task of unscheduledTasks) {
      if (task.recurrence) {
        const baseTaskText = task.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
        const recurrenceKey = `${baseTaskText}_${task.filePath}`;
        if (!seenRecurrenceKeys.has(recurrenceKey)) {
          seenRecurrenceKeys.add(recurrenceKey);
          uniqueUnscheduledTasks.push(task);
        }
      } else {
        uniqueUnscheduledTasks.push(task);
      }
    }
    if (uniqueUnscheduledTasks.length > 0) {
      this.renderUnscheduledTasks(container, uniqueUnscheduledTasks);
    }
  }
  async renderWeekView(container) {
    const grid = container.createDiv({ cls: "block-time-grid week-view" });
    const { startHour, endHour } = this.plugin.settings;
    const startOfWeek = this.getStartOfWeek(this.currentDate);
    const tasks = await this.taskParser.getTasksForWeek(startOfWeek);
    const daysHeader = grid.createDiv({ cls: "block-time-days-header" });
    daysHeader.createDiv({ cls: "block-time-corner" });
    const dayNames = [
      this.plugin.i18n.t("sunday"),
      this.plugin.i18n.t("monday"),
      this.plugin.i18n.t("tuesday"),
      this.plugin.i18n.t("wednesday"),
      this.plugin.i18n.t("thursday"),
      this.plugin.i18n.t("friday"),
      this.plugin.i18n.t("saturday")
    ];
    for (let d = 0; d < 7; d++) {
      const dayDate = new Date(startOfWeek);
      dayDate.setDate(dayDate.getDate() + d);
      const dayHeader = daysHeader.createDiv({ cls: "block-time-day-header" });
      dayHeader.createDiv({ cls: "day-name", text: dayNames[dayDate.getDay()] });
      dayHeader.createDiv({ cls: "day-number", text: dayDate.getDate().toString() });
      if (this.isToday(dayDate)) {
        dayHeader.addClass("today");
      }
    }
    const gridBody = grid.createDiv({ cls: "block-time-grid-body" });
    const hoursColumn = gridBody.createDiv({ cls: "block-time-hours-column" });
    for (let hour = startHour; hour <= endHour; hour++) {
      const hourSlot = hoursColumn.createDiv({ cls: "block-time-hour-label" });
      hourSlot.textContent = `${hour.toString().padStart(2, "0")}:00`;
    }
    for (let d = 0; d < 7; d++) {
      const dayDate = new Date(startOfWeek);
      dayDate.setDate(dayDate.getDate() + d);
      const dayColumn = gridBody.createDiv({ cls: "block-time-day-column" });
      if (this.isToday(dayDate)) {
        dayColumn.addClass("today");
      }
      for (let hour = startHour; hour <= endHour; hour++) {
        const hourSlot = dayColumn.createDiv({ cls: "block-time-hour-slot" });
        hourSlot.dataset.hour = hour.toString();
        hourSlot.dataset.day = d.toString();
        this.addSlotCreateHandler(hourSlot, hour, dayDate);
      }
      const dayTasks = tasks.filter((t) => t.date && this.isSameDay(t.date, dayDate));
      for (const task of dayTasks) {
        if (task.startTime) {
          this.renderTaskBlock(dayColumn, task, startHour);
        }
      }
    }
    const unscheduledTasks = tasks.filter((t) => !t.startTime && !t.completed);
    const uniqueUnscheduledTasks = [];
    const seenRecurrenceKeys = /* @__PURE__ */ new Set();
    for (const task of unscheduledTasks) {
      if (task.recurrence) {
        const baseTaskText = task.rawLine.replace(/^(\s*)-\s*\[[xX]\]\s*/, "").replace(/\s*✅\s*\d{4}-\d{2}-\d{2}/, "").trim();
        const recurrenceKey = `${baseTaskText}_${task.filePath}`;
        if (!seenRecurrenceKeys.has(recurrenceKey)) {
          seenRecurrenceKeys.add(recurrenceKey);
          uniqueUnscheduledTasks.push(task);
        }
      } else {
        uniqueUnscheduledTasks.push(task);
      }
    }
    if (uniqueUnscheduledTasks.length > 0) {
      this.renderUnscheduledTasks(container, uniqueUnscheduledTasks);
    }
  }
  renderTaskBlock(container, task, startHour) {
    if (!task.startTime)
      return;
    const [hours, minutes] = task.startTime.split(":").map(Number);
    const topOffset = (hours - startHour) * 60 + minutes;
    const height = task.duration;
    const block = container.createDiv({ cls: "block-time-task-block" });
    setCssProps(block, {
      top: `${topOffset}px`,
      height: `${Math.max(height, 30)}px`
    });
    block.addClass(`priority-${task.priority}`);
    if (task.completed) {
      block.addClass("completed");
    }
    const checkbox = block.createEl("input", { type: "checkbox", cls: "block-time-task-checkbox" });
    checkbox.checked = task.completed;
    checkbox.addEventListener("click", (e) => {
      e.stopPropagation();
      e.preventDefault();
      if (this.isToggling)
        return;
      this.isToggling = true;
      void (async () => {
        try {
          const api = this.plugin.getTasksApi();
          await this.taskParser.toggleTaskCompletion(task, api);
          await new Promise((resolve) => setTimeout(resolve, 500));
          await this.render();
        } finally {
          this.isToggling = false;
        }
      })();
    });
    const blockContent = block.createDiv({ cls: "block-time-task-content" });
    const timeLabel = blockContent.createDiv({ cls: "block-time-task-time" });
    timeLabel.textContent = task.endTime ? `${task.startTime} - ${task.endTime}` : task.startTime;
    const textLabel = blockContent.createDiv({ cls: "block-time-task-text" });
    textLabel.textContent = task.text || "Tarefa sem t\xEDtulo";
    blockContent.addEventListener("click", () => {
      void (async () => {
        const file = this.app.vault.getAbstractFileByPath(task.filePath);
        if (file instanceof import_obsidian.TFile) {
          await this.app.workspace.getLeaf(false).openFile(file);
        }
      })();
    });
    blockContent.addEventListener("dblclick", (e) => {
      e.stopPropagation();
      void (async () => {
        const api = this.plugin.getTasksApi();
        if (!api) {
          new import_obsidian.Notice("Tasks plugin not found. Install it to edit tasks from the calendar.");
          return;
        }
        const edited = await this.taskParser.editTaskLine(task, api);
        if (edited) {
          await new Promise((resolve) => setTimeout(resolve, 500));
          await this.render();
        }
      })();
    });
    const apiHint = this.plugin.getTasksApi() ? " | Duplo-clique para editar" : "";
    block.setAttribute("title", `${task.text}
\u{1F4C1} ${task.filePath}:${task.line}${apiHint}`);
  }
  renderUnscheduledTasks(container, tasks) {
    const section = container.createDiv({ cls: "block-time-unscheduled" });
    const heading = new import_obsidian.Setting(section);
    heading.setName(this.plugin.i18n.t("unscheduled-tasks"));
    heading.setHeading();
    heading.settingEl.remove();
    const list = section.createEl("ul", { cls: "block-time-unscheduled-list" });
    for (const task of tasks) {
      const item = list.createEl("li", { cls: `priority-${task.priority}` });
      if (task.completed)
        item.addClass("completed");
      const checkbox = item.createEl("input", { type: "checkbox" });
      checkbox.checked = task.completed;
      checkbox.addEventListener("click", (e) => {
        e.stopPropagation();
        e.preventDefault();
        if (this.isToggling)
          return;
        this.isToggling = true;
        void (async () => {
          try {
            const api = this.plugin.getTasksApi();
            await this.taskParser.toggleTaskCompletion(task, api);
            await new Promise((resolve) => setTimeout(resolve, 500));
            await this.render();
          } finally {
            this.isToggling = false;
          }
        })();
      });
      const textSpan = item.createSpan({ text: task.text || "Untitled task" });
      textSpan.addEventListener("click", () => {
        void (async () => {
          const file = this.app.vault.getAbstractFileByPath(task.filePath);
          if (file instanceof import_obsidian.TFile) {
            await this.app.workspace.getLeaf(false).openFile(file);
          }
        })();
      });
      textSpan.addEventListener("dblclick", (e) => {
        e.stopPropagation();
        void (async () => {
          const api = this.plugin.getTasksApi();
          if (!api)
            return;
          const edited = await this.taskParser.editTaskLine(task, api);
          if (edited) {
            await new Promise((resolve) => setTimeout(resolve, 500));
            await this.render();
          }
        })();
      });
    }
  }
  addSlotCreateHandler(slot, hour, date) {
    const api = this.plugin.getTasksApi();
    if (!api)
      return;
    slot.addClass("block-time-slot-clickable");
    slot.setAttribute("title", "Clique para criar task neste hor\xE1rio");
    slot.addEventListener("click", (e) => {
      if (e.target !== slot)
        return;
      void (async () => {
        var _a, _b;
        const taskLine = await api.createTaskLineModal();
        if (!taskLine)
          return;
        let targetPath;
        if (this.plugin.settings.taskCreationFolder.trim()) {
          const folder = this.plugin.settings.taskCreationFolder.trim();
          targetPath = folder.endsWith(".md") ? folder : `${folder}.md`;
        } else {
          targetPath = this.getDailyNotePath(date);
        }
        let file = this.app.vault.getAbstractFileByPath(targetPath);
        if (!file) {
          try {
            const parentDir = targetPath.substring(0, targetPath.lastIndexOf("/"));
            if (parentDir && !this.app.vault.getAbstractFileByPath(parentDir)) {
              await this.app.vault.createFolder(parentDir);
            }
            const fallbackName = date.toISOString().slice(0, 10);
            const fileName = (_b = (_a = targetPath.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) != null ? _b : fallbackName;
            file = await this.app.vault.create(targetPath, `# ${fileName}

`);
          } catch (e2) {
            new import_obsidian.Notice(`N\xE3o foi poss\xEDvel criar ${targetPath}`);
            return;
          }
        }
        if (!(file instanceof import_obsidian.TFile))
          return;
        const content = await this.app.vault.read(file);
        const hourStr = `${hour.toString().padStart(2, "0")}:00`;
        const lineToInsert = taskLine.includes(hourStr) ? taskLine : taskLine;
        const newContent = content.trimEnd() + "\n" + lineToInsert + "\n";
        await this.app.vault.modify(file, newContent);
        new import_obsidian.Notice(`Task criada em ${targetPath}`);
        await new Promise((resolve) => setTimeout(resolve, 500));
        await this.render();
      })();
    });
  }
  getDailyNotePath(date) {
    var _a, _b, _c, _d, _e, _f, _g;
    try {
      const appWithInternal = this.app;
      const dailyNotesPlugin = (_c = (_b = (_a = appWithInternal.internalPlugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["daily-notes"]) == null ? void 0 : _c.instance;
      const format = (_e = (_d = dailyNotesPlugin == null ? void 0 : dailyNotesPlugin.options) == null ? void 0 : _d.format) != null ? _e : "YYYY-MM-DD";
      const folder = (_g = (_f = dailyNotesPlugin == null ? void 0 : dailyNotesPlugin.options) == null ? void 0 : _f.folder) != null ? _g : "";
      const fileName = (0, import_obsidian.moment)(date).format(format);
      return folder ? `${folder}/${fileName}.md` : fileName;
    } catch (e) {
      const fileName = (0, import_obsidian.moment)(date).format("YYYY-MM-DD");
      return `${fileName}.md`;
    }
  }
  getStartOfWeek(date) {
    const d = new Date(date);
    const day = d.getDay();
    const diff = d.getDate() - day;
    return new Date(d.setDate(diff));
  }
  isToday(date) {
    const today = new Date();
    return this.isSameDay(date, today);
  }
  isSameDay(date1, date2) {
    return date1.getFullYear() === date2.getFullYear() && date1.getMonth() === date2.getMonth() && date1.getDate() === date2.getDate();
  }
};
var BlockTimeSettingTab = class extends import_obsidian.PluginSettingTab {
  // 30 segundos
  constructor(app, plugin) {
    super(app, plugin);
    // Cache para evitar reescaneamento desnecessário
    this.folderCache = null;
    this.folderTreeCache = null;
    this.CACHE_DURATION = 3e4;
    this.plugin = plugin;
  }
  // ============================================================================
  // MÉTODOS UTILITÁRIOS
  // ============================================================================
  getAllFolders() {
    const now = Date.now();
    if (this.folderCache && this.folderCache.folders.size > 0 && now - this.folderCache.timestamp < this.CACHE_DURATION) {
      return this.folderCache.folders;
    }
    const folders = /* @__PURE__ */ new Set();
    const files = this.app.vault.getFiles();
    for (const file of files) {
      const parts = file.path.split("/");
      let currentPath = "";
      for (const part of parts) {
        if (part === file.name)
          continue;
        currentPath = currentPath ? `${currentPath}/${part}` : part;
        folders.add(currentPath);
      }
    }
    this.folderCache = {
      folders,
      timestamp: now,
      fileCount: files.length
      // Mantido para logging, não usado na validação
    };
    return folders;
  }
  invalidateFolderCache() {
    if (this.folderCache || this.folderTreeCache) {
      this.folderCache = null;
      this.folderTreeCache = null;
    }
  }
  buildFolderTree(files) {
    const now = Date.now();
    if (this.folderTreeCache && this.folderTreeCache.tree.length > 0 && now - this.folderTreeCache.timestamp < this.CACHE_DURATION) {
      return this.folderTreeCache.tree;
    }
    const nodeMap = /* @__PURE__ */ new Map();
    for (const file of files) {
      const parts = file.path.split("/");
      let currentPath = "";
      for (const part of parts) {
        if (part === file.name)
          continue;
        const parentPath = currentPath;
        currentPath = parentPath ? `${parentPath}/${part}` : part;
        if (!nodeMap.has(currentPath)) {
          nodeMap.set(currentPath, {
            name: part,
            path: currentPath,
            children: []
          });
        }
        if (parentPath && nodeMap.has(parentPath)) {
          const parentNode = nodeMap.get(parentPath);
          const currentNode = nodeMap.get(currentPath);
          if (parentNode && currentNode && !parentNode.children.includes(currentNode)) {
            parentNode.children.push(currentNode);
          }
        }
      }
    }
    const tree = Array.from(nodeMap.values()).filter((node) => !node.path.includes("/"));
    this.folderTreeCache = {
      tree,
      timestamp: now,
      fileCount: files.length
      // Mantido para logging, não usado na validação
    };
    return tree;
  }
  parseSelectedFolders() {
    return this.plugin.settings.scanFolders.split(",").map((f) => f.trim().replace(/^\/+|\/+$/g, "")).filter((f) => f.length > 0);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("view-title")).setHeading();
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("settings-agenda")).setHeading();
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("start-hour")).setDesc(this.plugin.i18n.t("start-hour-desc")).addSlider((slider) => slider.setLimits(0, 12, 1).setValue(this.plugin.settings.startHour).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.startHour = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("end-hour")).setDesc(this.plugin.i18n.t("end-hour-desc")).addSlider((slider) => slider.setLimits(18, 24, 1).setValue(this.plugin.settings.endHour).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.endHour = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default view").setDesc("Choose between daily or weekly view").addDropdown((dropdown) => dropdown.addOption("day", "Daily").addOption("week", "Weekly").setValue(this.plugin.settings.defaultView).onChange(async (value) => {
      this.plugin.settings.defaultView = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("scan-folders")).setDesc(this.plugin.i18n.t("scan-folders-desc"));
    this.renderFolderPicker(containerEl);
    const infoBox = containerEl.createDiv({ cls: "setting-item-description block-time-info-box" });
    infoBox.createEl("strong", { text: this.plugin.i18n.t("info-title") });
    infoBox.createEl("br");
    infoBox.createEl("br");
    infoBox.createEl("span", { text: this.plugin.i18n.t("info-para1") });
    infoBox.createEl("br");
    infoBox.createEl("br");
    infoBox.createEl("span", { text: this.plugin.i18n.t("info-para2") });
    infoBox.createEl("br");
    infoBox.createEl("br");
    infoBox.createEl("span", { text: this.plugin.i18n.t("info-para3") });
    infoBox.createEl("br");
    infoBox.createEl("br");
    infoBox.createEl("em", { text: this.plugin.i18n.t("info-footer") });
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("settings-appearance")).setHeading();
    new import_obsidian.Setting(containerEl).setName("Use Obsidian theme").setDesc("Inherit colors from active theme (including downloaded themes). Disable to use plugin default colors.").addToggle((toggle) => toggle.setValue(this.plugin.settings.useObsidianTheme).onChange(async (value) => {
      this.plugin.settings.useObsidianTheme = value;
      await this.plugin.saveSettings();
      this.app.workspace.getLeavesOfType(VIEW_TYPE_BLOCK_TIME).forEach((leaf) => {
        const view = leaf.view;
        if (view.render)
          void view.render();
      });
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("settings-notifications")).setHeading();
    new import_obsidian.Setting(containerEl).setName("Enable notifications").setDesc("Desktop and in-app notifications when a scheduled task is about to start.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableNotifications).onChange(async (value) => {
      this.plugin.settings.enableNotifications = value;
      await this.plugin.saveSettings();
      if (value) {
        this.plugin.startNotificationScheduler();
      } else {
        this.plugin.stopNotificationScheduler();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Early reminder").setDesc("Extra notification before task time.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableReminderBefore).onChange(async (value) => {
      this.plugin.settings.enableReminderBefore = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Minutes before").setDesc("How many minutes before task time you want to be reminded.").addSlider((slider) => slider.setLimits(1, 60, 1).setValue(this.plugin.settings.reminderMinutesBefore).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.reminderMinutesBefore = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("settings-deadlines")).setHeading();
    new import_obsidian.Setting(containerEl).setName("Enable deadline reminders").setDesc("Notify about tasks with deadline tags approaching due date.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableDeadlineReminders).onChange(async (value) => {
      this.plugin.settings.enableDeadlineReminders = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Deadline tags").setDesc("Tags that identify tasks with deadlines. Comma separated.").addText((text) => text.setPlaceholder("#prazo, #deadline").setValue(this.plugin.settings.deadlineTags).onChange(async (value) => {
      this.plugin.settings.deadlineTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Days before").setDesc("How many days before deadline to start notifying.").addSlider((slider) => slider.setLimits(1, 30, 1).setValue(this.plugin.settings.deadlineReminderDays).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.deadlineReminderDays = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily reminder time").setDesc("Time from which deadline reminder triggers (once per day).").addSlider((slider) => slider.setLimits(6, 22, 1).setValue(this.plugin.settings.deadlineReminderHour).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.deadlineReminderHour = value;
      await this.plugin.saveSettings();
    }));
    const detailsEl = containerEl.createEl("details", { cls: "block-time-settings-details" });
    detailsEl.createEl("summary", { text: this.plugin.i18n.t("settings-texts") });
    const detailsContent = detailsEl.createDiv({ cls: "block-time-settings-details-content" });
    detailsContent.createEl("p", {
      text: "Placeholders: {task} {min} {days} {time} {endTime} {file} {date}",
      cls: "setting-item-description"
    });
    const templateSettings = [
      { key: "notifyTextEarlyTask", name: "Early reminder", desc: "X min before task" },
      { key: "notifyTextOnTimeTask", name: "On time", desc: "Exact task time" },
      { key: "notifyTextDeadlineEarly", name: "Deadline \u2014 min before", desc: "X min before deadline" },
      { key: "notifyTextDeadlineNow", name: "Deadline \u2014 now", desc: "Exact deadline time" },
      { key: "notifyTextDeadlineToday", name: "Deadline \u2014 today", desc: "Deadline is today (no time)" },
      { key: "notifyTextDeadlineDays", name: "Deadline \u2014 days", desc: "X days until deadline" }
    ];
    for (const tmpl of templateSettings) {
      new import_obsidian.Setting(detailsContent).setName(tmpl.name).setDesc(tmpl.desc).addText((text) => text.setValue(this.plugin.settings[tmpl.key]).onChange(async (value) => {
        this.plugin.settings[tmpl.key] = value;
        await this.plugin.saveSettings();
      }));
    }
  }
  renderFolderPicker(containerEl) {
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("advanced-folder-mode")).setDesc(this.plugin.i18n.t("advanced-folder-mode-desc")).addToggle((toggle) => toggle.setValue(false).onChange((value) => {
      this.renderFolderPickerWithMode(pickerContainer, value);
    }));
    const pickerContainer = containerEl.createDiv({ cls: "block-time-folder-picker-container" });
    this.renderFolderPickerWithMode(pickerContainer, false);
  }
  renderFolderPickerWithMode(containerEl, advancedMode) {
    containerEl.empty();
    if (advancedMode) {
      this.renderAdvancedFolderPicker(containerEl);
    } else {
      this.renderSimpleFolderPicker(containerEl);
    }
  }
  renderSimpleFolderPicker(containerEl) {
    new import_obsidian.Setting(containerEl).setName(this.plugin.i18n.t("scan-folders")).setDesc(this.plugin.i18n.t("scan-folders-desc")).addText((text) => {
      const folders = this.getAllFolders();
      new FolderSuggest(this.app, text.inputEl, folders);
      return text.setPlaceholder("Example: folder1, folder2/subfolder").setValue(this.plugin.settings.scanFolders).onChange(async (value) => {
        this.plugin.settings.scanFolders = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Folder for task creation").setDesc("Folder or file path where new tasks will be created (default: task)").addText((text) => {
      const folders = this.getAllFolders();
      new FolderSuggest(this.app, text.inputEl, folders);
      return text.setPlaceholder("Example: task or Tasks/MyTasks").setValue(this.plugin.settings.taskCreationFolder).onChange(async (value) => {
        this.plugin.settings.taskCreationFolder = value;
        await this.plugin.saveSettings();
      });
    });
  }
  renderAdvancedFolderPicker(containerEl) {
    const selectedFolders = this.parseSelectedFolders();
    const pickerEl = containerEl.createDiv({ cls: "block-time-folder-picker" });
    const tagsEl = pickerEl.createDiv({ cls: "block-time-folder-tags" });
    const renderTags = () => {
      tagsEl.empty();
      if (selectedFolders.length === 0) {
        tagsEl.createSpan({ text: this.plugin.i18n.t("no-folders-selected"), cls: "block-time-folder-hint" });
        return;
      }
      for (const folder of selectedFolders) {
        const tag = tagsEl.createSpan({ cls: "block-time-folder-tag" });
        tag.createSpan({ text: folder });
        const removeBtn = tag.createSpan({ text: " \u2715", cls: "block-time-folder-tag-remove" });
        removeBtn.addEventListener("click", () => {
          void (async () => {
            selectedFolders.splice(selectedFolders.indexOf(folder), 1);
            this.plugin.settings.scanFolders = selectedFolders.join(", ");
            await this.plugin.saveSettings();
            renderTags();
            renderTree();
          })();
        });
      }
    };
    renderTags();
    const searchContainer = pickerEl.createDiv({ cls: "block-time-folder-search" });
    const searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: "Buscar pasta...",
      cls: "block-time-folder-search-input"
    });
    const treeEl = pickerEl.createDiv({ cls: "block-time-folder-tree" });
    const expandedSet = /* @__PURE__ */ new Set();
    const renderNode = (node, depth = 0, filterQuery = "") => {
      if (filterQuery && !node.name.toLowerCase().includes(filterQuery.toLowerCase())) {
        return;
      }
      const rowEl = treeEl.createDiv({ cls: "block-time-folder-row" });
      setCssProps(rowEl, { "padding-left": `${depth * 16}px` });
      const cb = rowEl.createEl("input", { type: "checkbox", cls: "block-time-folder-cb" });
      cb.checked = selectedFolders.includes(node.path);
      cb.addEventListener("change", () => {
        void (async () => {
          if (cb.checked) {
            if (!selectedFolders.includes(node.path)) {
              selectedFolders.push(node.path);
            }
          } else {
            const index = selectedFolders.indexOf(node.path);
            if (index > -1) {
              selectedFolders.splice(index, 1);
            }
          }
          this.plugin.settings.scanFolders = selectedFolders.join(", ");
          await this.plugin.saveSettings();
          renderTags();
        })();
      });
      if (node.children.length > 0) {
        const arrow = rowEl.createSpan({ cls: "block-time-folder-arrow has-children" });
        arrow.textContent = expandedSet.has(node.path) ? "\u25BC" : "\u25B6";
        arrow.addEventListener("click", (e) => {
          e.stopPropagation();
          if (expandedSet.has(node.path)) {
            expandedSet.delete(node.path);
          } else {
            expandedSet.add(node.path);
          }
          renderTree();
        });
      }
      const label = rowEl.createSpan({ cls: "block-time-folder-label" });
      label.textContent = node.name;
      rowEl.addEventListener("click", () => {
        cb.checked = !cb.checked;
        cb.dispatchEvent(new Event("change"));
      });
      if (node.children.length > 0 && expandedSet.has(node.path)) {
        for (const child of node.children) {
          renderNode(child, depth + 1, filterQuery);
        }
      }
    };
    const renderTree = (filterQuery = "") => {
      treeEl.empty();
      const allFiles = this.app.vault.getFiles();
      const folderTree = this.buildFolderTree(allFiles);
      for (const node of folderTree) {
        renderNode(node, 0, filterQuery);
      }
    };
    searchInput.addEventListener("input", () => {
      const query = searchInput.value.toLowerCase().trim();
      renderTree(query);
    });
    pickerEl.addEventListener("click", () => {
      searchInput.focus();
      renderTree(searchInput.value);
    });
    renderTree();
  }
};
